title: FRC8725's Blog
owner: FRC8725 Misty Panther
description: KEEP GOING & DREAM IT
language: zh-TW
timeZone: '+0800'
timeFormat: '%Y/%m/%d'
siteUrl: https://frc8725.github.io/FRC8725-Blog/

# twitter:
#   site: '@jhou5846'
#   creator: '@jhou5846'
#! liker:
#!   account: likerId

iconPath: 
  ico: image/configImage/icon.ico
  png: image/configImage/icon.png

avatarPath: image/configImage/avatar.png

badges:
  - icon: 🔬
    message: Science
  - icon: 💻
    message: Technology
  - icon: 🪛
    message: Engineering

tabs:
  home:
    text: Home
  about:
    text: About
    path: about.md
  articles:
    text: Articles
  portfolio:
    text: Portfolio
tabsAmount: 4

switches:
  rssUrl:
    text: Copy RSS
  backgroundMusic:
    text: BG Music
    path: audio/lofi.wav
    volume: 0.5
  darkMode:
    text: Dark Mode
switchesAmount: 3

pages: 
  filter:
    text: Filter
    search: Search
    archives: Archives
    categories: Categories
    tags: Tags
  outline:
    text: Outline

category:
  - name: Programming
    color:
      bright: '143, 170, 220'
      dark: '113, 140, 190'

  - name: Electronics
    color:
      bright: '255, 217, 98'
      dark: '255, 217, 98'

  - name: Activity
    color:
      bright: '222, 170, 166'
      dark: '192, 140, 136'
  - name: Crescendo
    color:
      bright: '64, 178, 123'
      dark: '64, 178, 123'
  - name: Artificial_Intelligence
    color:
      bright: '70, 102, 204'
      dark: '70, 163, 255'